### ISSUE TITLE
2017.4.28字符串的长度

### ISSUE THREAD

**Issue by qq20004604** [shanghaife/everyJS#2]
1、获取任意字符串的正确长度

> 题目描述：

我们需要正确的获知一个字符串的长度。作为示例，需要判断的字符串如下：

**基础：**
```
"";    //空字符串
"a b";    //2个字母加一个空白符
"a b\nc";    //上一行基础上加换行符加第3个字母
```

**进阶（参考规则2.4）**
```
"\uD83D\uDC2A\na"；    //1个unicode字符+换行符+字母a
"\uD83D\uDC2A\na b";    //1个unicode字符+换行符+字母a+空白符+字母b
```
---
> 题目要求：

**基础：**

在符合规则的前提下，封装一个函数，参数是字符串，返回值是字符串的长度。

**进阶：**

增加对非字符串的错误处理，错误的输入内容，值应返回-1，表示错误。

例如输入一个对象，应返回-1。

---

> 题目补充：

1、建议利用 **正则表达式** 来正确的获得其长度。

主要功能通过正则表达式实现，并非只允许使用正则表达式。

2、确定长度的规则如下：

**2.1、空白符、行终止符**

空白符与行终止符，不在判断范围之内（其不计算在长度之内）。

在判断字符串长度时，我们这里应认为以下两种字符不被计算在length之内：

1. 行终止符，例如"\n"这样的字符；
2. 空白符，例如空格、tab字符等，更具体的说，是可以被/\s/所匹配到的字符；

<br>

**2.2、支持多行匹配**

具体来说，上面的字符串"\uD83D\uDC2A\na"就是多行字符（两行），应能正确判断他的长度

**2.3、在以上规则的基础上，应支持任意字符串的长度判断。**

**2.4（进阶）Unicode字符**

unicode字符在码点大于\uFFFF的时候，长度应仍为1，而非通过leng属性返回的2。

例如：

```
"\uD83D\uDC2A";    //一个小马样子的字符
"\uD83D\uDC2A".length;    //2。事实上，他的length应该为1
```

*注：unicode字符涉及到es6的知识*

**2.5、以题目中字符串为例；**

基础部分：

第一个字符串的长度应为0；<br>
第二个字符串长度应为2————2个字符，空白符被忽略；<br>
第三字符长度为3————3个字符，空白符和换行符被忽略；

进阶部分：

第一个字符串长度为2————1个unicode字符加一个字母a，换行符被忽略；<br>
第二个字符串长度应为3————1个unicode字符加两个字母，换行符和空白符被忽略；

---
> 出题人

零零水<br>
QQ:20004604

**Comment by 94cstyles** [comment]
```javascript
function realLength (str) {
    return Object.prototype.toString.call(str) === '[object String]' ? (str.match(/([\uD800-\uDBFF][\uDC00-\uDFFF]|\S)/g) || []).length : -1
  }
```
**无懈可击了吧!* @qq20004604

**Comment by qq20004604** [comment]
@94cstyles 
上面的答案蛮不错的，不过还是要挑个刺（不挑刺没法进步对吧）：
`var a = new String("ABC");
realLength(a);     //-1`
